name: Docker build

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repository
            uses: actions/checkout@v2

            - name: Login to Docker Hub
            uses: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            - name: Docker Build
            uses: docker build -t onesto/music-api:latest .

            - name: Docker Push
            uses: docker push onesto/music-api:latest
