name: Docker build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Docker Build
        run: docker build -t onesto/music-api:latest .

      - name: Docker Push
        run: docker push onesto/music-api:latest

  migrate-db:
     runs-on: ubuntu-latest
     needs: build
     steps:
        - name: Run database migration
          run: |
            docker run --rm \
            -e DATABASE_HOST=${{ secrets.DATABASE_HOST }} \
            -e DATABASE_PORT=${{ secrets.DATABASE_PORT }} \
            -e DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} \
            -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
            -e DATABASE_NAME=${{ secrets.DATABASE_NAME }} \
            onesto/music-api:latest migrate --yes
